### ISSUE TITLE
Upgrade dos componentes de backend

### ISSUE THREAD

**Issue by tatosjb** [fabioelizandro/tap#11]
Fazer upgrade dos componentes de backend  para as versões mais recentes.

**Comment by fabioelizandro** [comment]
faltaram alguma dependências, utilizar David para referência

[https://david-dm.org/fabioelizandro/tap](https://david-dm.org/fabioelizandro/tap)
[https://david-dm.org/fabioelizandro/tap#info=devDependencies](https://david-dm.org/fabioelizandro/tap#info=devDependencies)
